### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [LessPaperWork/LessPaper.Shared.Queueing#4]
It has been noticed that while using getong/rabbitmq-action@v1.2 your rabbitmq password guest is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by ChristianHellwig** [comment]
Hi, thanks for the tip. However, the rabbitmq action creates a new rabbit mq instance in the github virtual machine and is only accessible from there. Accordingly, the credentials cannot be used elsewhere and using secrets would not provide effective additional protection.
